spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/testDb?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        #use_sql_comments: true
    open-in-view: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

logging.level:
  org.hibernate.SQL: debug

server:
  error:
    include-binding-errors: never
    include-exception: false
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: true
    path: /error